### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by JasonQAQ** [VitoLin21/Rodent-Skull-Stripping#2]
Hello Vito, I just tried running RS2_predict with the model you released and encountered an error. I placed a T2 nifti of a mouse in my RSStest folder, named T2_0000.nii.gz. The error message and code are as follows:
![Screenshot from 2024-03-07 15-12-39](https://github.com/VitoLin21/Rodent-Skull-Stripping/assets/20941010/7c958e13-2546-4e0f-98b9-d211378a1e49)

**Comment by VitoLin21** [comment]
I was wondering if your server has nvidia GPU? If not, you can add `-device cpu` after the command to use cpu for skull stripping.
Additionally, the majority of the dataset used for training is from the T1, and the performance on T2 may not be particularly good.

**Comment by JasonQAQ** [comment]
Thanks.will you be training with the T2 dataset? Because the brain structure of mice generally prefers T2-weighted images rather than T1-weighted images.

> I was wondering if your server has nvidia GPU? If not, you can add `-device cpu` after the command to use cpu for skull stripping. Additionally, the majority of the dataset used for training is from the T1, and the performance on T2 may not be particularly good.

**Comment by JasonQAQ** [comment]
> I was wondering if your server has nvidia GPU? If not, you can add `-device cpu` after the command to use cpu for skull stripping. Additionally, the majority of the dataset used for training is from the T1, and the performance on T2 may not be particularly good.

I managed to run it successfully on a CPU, but indeed, the performance on T2 images was not good.

**Comment by VitoLin21** [comment]
Sorry, I made a mistake earlier. The majority of the data we use is T2-weighted (T2W), with some inclusion of T1 images. The primary sources for our data are two datasets: [multi_rats](https://openneuro.org/datasets/ds004114/versions/1.0.0) and [std_rats](https://openneuro.org/datasets/ds004116/versions/1.0.0).

However, for the mouse dataset, we have collected only a small amount (26 images), mostly consisting of T2-weighted data from rats. As a result, the performance on mouse data may not be optimal. If you are willing, could you please provide one or several data files from your recent test via email (my email: vitolin21@foxmail.com) or any other convenient method? I would like to try and evaluate the performance on those specific datasets.

**Comment by JasonQAQ** [comment]
Hello Vito, the issue with the CUDA error has been resolved. I deleted "index=1" from line 117 in predict.py. And I've sent an email with one of my T2 mouse.

**Comment by VitoLin21** [comment]
Thank you very much! I have received your email and fixed the code. Now the cuda device with index=0 will be used by default. I have been testing on multi-card servers when testing, so I have never found this problem.
Thank you for your feedback!
